// apps/backend/src/socket/events/events.js
import { PubSub } from 'graphql-subscriptions';

export const pubsub = new PubSub();

export const EVENTS = {
  // User Events
  USER_UPDATED: 'USER_UPDATED',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
  
  // Chat Events
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_UPDATED: 'MESSAGE_UPDATED',
  MESSAGE_DELETED: 'MESSAGE_DELETED',
  TYPING_STATUS: 'TYPING_STATUS',
  
  // Notification Events
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  
  // Solution Events
  SOLUTION_CREATED: 'SOLUTION_CREATED',
  SOLUTION_UPDATED: 'SOLUTION_UPDATED',
  SOLUTION_RATED: 'SOLUTION_RATED',
  
  // Job Events
  JOB_CREATED: 'JOB_CREATED',
  JOB_UPDATED: 'JOB_UPDATED',
  APPLICATION_RECEIVED: 'APPLICATION_RECEIVED',
  APPLICATION_STATUS_CHANGED: 'APPLICATION_STATUS_CHANGED',
  
  // Marketplace Events
  LISTING_CREATED: 'LISTING_CREATED',
  LISTING_UPDATED: 'LISTING_UPDATED',
  PURCHASE_COMPLETED: 'PURCHASE_COMPLETED',
  BOUNTY_CREATED: 'BOUNTY_CREATED',
  BOUNTY_SUBMISSION: 'BOUNTY_SUBMISSION',
  
  // Squad Events
  SQUAD_CREATED: 'SQUAD_CREATED',
  SQUAD_UPDATED: 'SQUAD_UPDATED',
  SQUAD_MEMBER_JOINED: 'SQUAD_MEMBER_JOINED',
  SQUAD_MEMBER_LEFT: 'SQUAD_MEMBER_LEFT',
  
  // Subscription Events
  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_UPDATED: 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  
  // Payment Events
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  REFUND_PROCESSED: 'REFUND_PROCESSED',
  
  // Advertisement Events
  CAMPAIGN_CREATED: 'CAMPAIGN_CREATED',
  CAMPAIGN_UPDATED: 'CAMPAIGN_UPDATED',
  CAMPAIGN_STATUS_CHANGED: 'CAMPAIGN_STATUS_CHANGED',
  AD_CREATED: 'AD_CREATED',
  AD_UPDATED: 'AD_UPDATED',
  AD_STATUS_CHANGED: 'AD_STATUS_CHANGED',
  AD_PERFORMANCE_UPDATED: 'AD_PERFORMANCE_UPDATED',
  BUDGET_ALERT: 'BUDGET_ALERT',
  APPROVAL_STATUS_CHANGED: 'APPROVAL_STATUS_CHANGED',
  
  // Admin Events
  ADMIN_ACTION: 'ADMIN_ACTION',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
  AUDIT_LOG_CREATED: 'AUDIT_LOG_CREATED',
  
  // Presence Events
  USER_ONLINE: 'USER_ONLINE',
  USER_OFFLINE: 'USER_OFFLINE',
  USER_AWAY: 'USER_AWAY',
  
  // Announcement Events
  ANNOUNCEMENT_CREATED: 'ANNOUNCEMENT_CREATED',
  ANNOUNCEMENT_UPDATED: 'ANNOUNCEMENT_UPDATED',
};

export default { pubsub, EVENTS };